name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set blue color
        run: echo "Deployed"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Print Greeting
        run: echo "Hello World!"

